// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using his_backend.Models;

#nullable disable

namespace his_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305022546_addDBDmchuyenkhoa")]
    partial class addDBDmchuyenkhoa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("his_backend.Models.AppUser", b =>
                {
                    b.Property<int>("Mand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mand");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Mand"));

                    b.Property<string>("Cccd")
                        .HasColumnType("text");

                    b.Property<string>("DanToc")
                        .HasColumnType("text");

                    b.Property<string>("DiaChiChiTiet")
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hoten");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<DateTimeOffset?>("LanDangNhapCuoi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("landangnhapcuoi");

                    b.Property<string>("Mabn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mabn");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("matkhauhash");

                    b.Property<DateTimeOffset>("NgayCapCccd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("QuocTich")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenHetHan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_het_han");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("sodienthoai");

                    b.Property<string>("TenThanhPho")
                        .HasColumnType("text");

                    b.Property<string>("TenXa")
                        .HasColumnType("text");

                    b.Property<string>("TonGiao")
                        .HasColumnType("text");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("user")
                        .HasColumnName("vaitro");

                    b.HasKey("Mand");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasDatabaseName("app_users_sdt_unique");

                    b.ToTable("app_users", "benhnhan");
                });

            modelBuilder.Entity("his_backend.Models.Dmchuyenkhoa", b =>
                {
                    b.Property<int>("Mack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mack");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Mack"));

                    b.Property<string>("MoTaTrieuChung")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mota_trieuchung");

                    b.Property<string>("TenCk")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tenck");

                    b.HasKey("Mack");

                    b.ToTable("dmchuyenkhoa", "benhnhan");
                });
#pragma warning restore 612, 618
        }
    }
}
