// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using his_backend.Models;

#nullable disable

namespace his_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309072327_themdangkykham")]
    partial class themdangkykham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("his_backend.Models.AppUser", b =>
                {
                    b.Property<int>("Mand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mand");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Mand"));

                    b.Property<string>("Bhxh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bhxh");

                    b.Property<string>("Cmnd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cmnd");

                    b.Property<string>("Diachi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("diachi");

                    b.Property<decimal?>("Gioitinh")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("gioitinh");

                    b.Property<string>("Holot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("holot");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<DateTimeOffset?>("LanDangNhapCuoi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("landangnhapcuoi");

                    b.Property<string>("Madt")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("madt");

                    b.Property<string>("Maloaigiayto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("maloaigiayto");

                    b.Property<string>("Manghe")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("manghe");

                    b.Property<string>("Maqg")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("VN")
                        .HasColumnName("maqg");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("matkhauhash");

                    b.Property<string>("Matinh")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matinh");

                    b.Property<string>("Maxa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("maxa");

                    b.Property<DateTimeOffset>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngaytao")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("Ngaycap")
                        .HasColumnType("date")
                        .HasColumnName("ngaycap");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("NhomMau")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nhommau");

                    b.Property<string>("Noicap")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("noicap");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenHetHan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_het_han");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("sodienthoai");

                    b.Property<string>("Ten")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ten");

                    b.HasKey("Mand");

                    b.HasIndex("Cmnd")
                        .HasDatabaseName("app_users_cmnd_idx");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasDatabaseName("app_users_sdt_unique");

                    b.ToTable("app_users", "benhnhan");
                });

            modelBuilder.Entity("his_backend.Models.AppUserHoSo", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("integer")
                        .HasColumnName("appuserid");

                    b.Property<int>("HoSoId")
                        .HasColumnType("integer")
                        .HasColumnName("hosoid");

                    b.Property<bool>("LaMacDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lamacdinh");

                    b.Property<DateTimeOffset>("NgayLienKet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngaylienket")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("ban_than")
                        .HasColumnName("quanhe");

                    b.HasKey("AppUserId", "HoSoId");

                    b.HasIndex("HoSoId");

                    b.ToTable("app_user_hoso", "benhnhan");
                });

            modelBuilder.Entity("his_backend.Models.DangKyKham", b =>
                {
                    b.Property<int>("MaDk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("madk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaDk"));

                    b.Property<string>("Bhyt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bhyt");

                    b.Property<string>("Cmnd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cmnd");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("diachi");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ghichu");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("giatien");

                    b.Property<string>("HiqrCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hiqrcode");

                    b.Property<int>("HisId")
                        .HasColumnType("integer")
                        .HasColumnName("hisid");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hoten");

                    b.Property<string>("LoaiBenhNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("loaibenhnhan");

                    b.Property<string>("LoaiKham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("loaikham");

                    b.Property<string>("MaCk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mack");

                    b.Property<int>("Mabn")
                        .HasColumnType("integer")
                        .HasColumnName("mabn");

                    b.Property<int>("Mabs")
                        .HasColumnType("integer")
                        .HasColumnName("mabs");

                    b.Property<int>("Mapk")
                        .HasColumnType("integer")
                        .HasColumnName("mapk");

                    b.Property<string>("MngthisId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mngthisid");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("date")
                        .HasColumnName("ngay");

                    b.Property<DateTime>("NgaySua")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngaysua");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<decimal>("Phidv")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("phidv");

                    b.Property<decimal>("Phikham")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("phikham");

                    b.Property<decimal>("Phithuoc")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("phithuoc");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("quanhe");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sdt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenNguoiThan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tennguoithan");

                    b.Property<DateTime>("TimeSlot")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeslot");

                    b.Property<decimal>("TrangThai")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("trangthai");

                    b.Property<bool>("Xoa")
                        .HasColumnType("boolean")
                        .HasColumnName("xoa");

                    b.HasKey("MaDk");

                    b.ToTable("dangkykham", "benhnhan");
                });

            modelBuilder.Entity("his_backend.Models.Dmchuyenkhoa", b =>
                {
                    b.Property<int>("Mack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mack");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Mack"));

                    b.Property<string>("MoTaTrieuChung")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mota_trieuchung");

                    b.Property<string>("TenCk")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tenck");

                    b.HasKey("Mack");

                    b.ToTable("dmchuyenkhoa", "benhnhan");
                });

            modelBuilder.Entity("his_backend.Models.Nguoibenhdangky", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Bhxh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bhxh");

                    b.Property<string>("Cmnd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cmnd");

                    b.Property<string>("Diachi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("diachi");

                    b.Property<decimal?>("Gioitinh")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("gioitinh");

                    b.Property<string>("Holot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("holot");

                    b.Property<string>("Madt")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("madt");

                    b.Property<string>("Maloaigiayto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("maloaigiayto");

                    b.Property<string>("Manghe")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("manghe");

                    b.Property<string>("Maqg")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("VN")
                        .HasColumnName("maqg");

                    b.Property<string>("Matinh")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matinh");

                    b.Property<string>("Maxa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("maxa");

                    b.Property<DateOnly?>("Ngaycap")
                        .HasColumnType("date")
                        .HasColumnName("ngaycap");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("NhomMau")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nhommau");

                    b.Property<string>("Noicap")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("noicap");

                    b.Property<string>("Sodienthoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sodienthoai");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id");

                    b.HasIndex("Cmnd")
                        .HasDatabaseName("nguoibenhdangky_cmnd_idx");

                    b.ToTable("nguoibenhdangky", "benhnhan");
                });

            modelBuilder.Entity("his_backend.Models.AppUserHoSo", b =>
                {
                    b.HasOne("his_backend.Models.AppUser", "AppUser")
                        .WithMany("HoSoLienKets")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("his_backend.Models.Nguoibenhdangky", "HoSo")
                        .WithMany("UserLienKets")
                        .HasForeignKey("HoSoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("HoSo");
                });

            modelBuilder.Entity("his_backend.Models.AppUser", b =>
                {
                    b.Navigation("HoSoLienKets");
                });

            modelBuilder.Entity("his_backend.Models.Nguoibenhdangky", b =>
                {
                    b.Navigation("UserLienKets");
                });
#pragma warning restore 612, 618
        }
    }
}
